export enum Role {
    ADMIN = 'ADMIN',
    STUDENT ='STUDENT',
    PRINCIPAL = 'PRINCIPAL',
    COLLEGE_ADMIN='COLLEGE_ADMIN',
    TEACHER = 'TEACHER',
    EXAM_COORDINATOR = 'EXAM_COORDINATOR',
    EXAM_CONTROLLER = 'EXAM_CONTROLLER'
  }
  